### GET vocabs
GET http://localhost:8000/vocab/aeb7c97a-880f-4d26-aa6e-1b1af074a9c9

### GET Multiple Choice for User with ID 123
GET http://localhost:8000/multiple-choice/aeb7c97a-880f-4d26-aa6e-1b1af074a9c9/2

### POST
POST http://localhost:8000/conversation
Content-Type: application/json

{
  "user_id": "123",
  "message": "Hello, how are you? My name is John."
}

### POST Chat Conversation
POST http://localhost:8000/chat_conversation
Content-Type: application/json

{
  "user_id": "user123",
  "message": "Can you help me with this problem: I am going to the store later today.. Explain the grammar and vocabulary used in this sentence."
}

### Test GET
GET http://localhost:8000/learning_path/user123

### GET status
GET http://localhost:8000/learning_path/user123/4d00476b-b3f6-4f83-bfd3-1242316b11b3